/**
 * Items — child rows of an item request. quantity_claimed moves ONLY through
 * record_item_pledge() (replit.md rule 2); no function here can touch it, and
 * quantity_remaining is generated by the database.
 */
import type { PoolClient } from "pg";
import { q, withDbContext, type DbContext } from "../db/client";
import type { Item, ItemCondition } from "../../shared/types";

const COLS = `id, legacy_wix_id as "legacyWixId", item_request_id as "itemRequestId", name, description,
  condition, product_url as "productUrl", quantity_requested as "quantityRequested",
  quantity_claimed as "quantityClaimed", quantity_received as "quantityReceived",
  quantity_remaining as "quantityRemaining", sort_order as "sortOrder",
  created_at as "createdAt", updated_at as "updatedAt"`;

export type CreateItemInput = {
  name: string;
  description?: string | null;
  condition?: ItemCondition | null;
  productUrl?: string | null;
  quantityRequested: number;
  sortOrder?: number;
};

/** Patch type deliberately has no quantityClaimed/quantityRemaining. */
export type UpdateItemPatch = Partial<{
  name: string;
  description: string | null;
  condition: ItemCondition | null;
  productUrl: string | null;
  quantityRequested: number;
  quantityReceived: number;
  sortOrder: number;
}>;

/** Complete staff-edit row used by the request correction flow. */
export type ReplaceItemInput = {
  /** Omit for a new row. Existing ids must belong to this request. */
  id?: string;
  name: string;
  description: string;
  condition: ItemCondition;
  productUrl: string | null;
  quantityRequested: number;
};

export class RequestMustRetainAnItemError extends Error {
  constructor() {
    super("Add at least one item before saving this request.");
    this.name = "RequestMustRetainAnItemError";
  }
}

export class ItemWithActivityCannotBeRemovedError extends Error {
  constructor(itemName: string) {
    super(`"${itemName}" cannot be removed because donors have already participated in it.`);
    this.name = "ItemWithActivityCannotBeRemovedError";
  }
}

export class ItemQuantityBelowParticipationError extends Error {
  constructor(itemName: string, floor: number) {
    super(`"${itemName}" must request at least ${floor} because ${floor} have already been claimed or received.`);
    this.name = "ItemQuantityBelowParticipationError";
  }
}

export class RequestHasItemActivityError extends Error {
  constructor() {
    super("item request has donor or fulfillment activity");
    this.name = "RequestHasItemActivityError";
  }
}

export class UnknownItemOnRequestError extends Error {
  constructor() {
    super("one or more items do not belong to this request");
    this.name = "UnknownItemOnRequestError";
  }
}

export async function assertNoItemActivityInTx(c: PoolClient, requestId: string): Promise<Item[]> {
  const existing = await q<Item>(c, `select ${COLS} from items where item_request_id = $1 for update`, [requestId]);
  if (
    existing.some((item) => item.quantityClaimed !== 0 || item.quantityReceived !== 0) ||
    (
      await q<{ exists: boolean }>(
        c,
        `select exists(select 1 from item_pledges where item_request_id = $1) as exists`,
        [requestId],
      )
    )[0]?.exists
  ) {
    throw new RequestHasItemActivityError();
  }
  return existing;
}

const PATCH_COLUMNS: Record<keyof UpdateItemPatch, string> = {
  name: "name",
  description: "description",
  condition: "condition",
  productUrl: "product_url",
  quantityRequested: "quantity_requested",
  quantityReceived: "quantity_received",
  sortOrder: "sort_order",
};

/** Items of a request in sort order (MP-08 list, PB-02 table). */
export async function listByRequest(ctx: DbContext, requestId: string): Promise<Item[]> {
  return withDbContext(ctx, (c) =>
    q<Item>(c, `select ${COLS} from items where item_request_id = $1 order by sort_order asc, created_at asc`, [
      requestId,
    ]),
  );
}

export async function getById(ctx: DbContext, itemId: string): Promise<Item | null> {
  const rows = await withDbContext(ctx, (c) => q<Item>(c, `select ${COLS} from items where id = $1`, [itemId]));
  return rows[0] ?? null;
}

/**
 * Add an item to a request (MP-08). The request must belong to the session
 * organization — verified in SQL, with RLS as the backstop.
 */
export async function create(ctx: DbContext, orgId: string, requestId: string, input: CreateItemInput): Promise<Item> {
  return withDbContext(ctx, async (c) => {
    const owner = await q<{ id: string }>(c, `select id from item_requests where id = $1 and org_id = $2`, [
      requestId,
      orgId,
    ]);
    if (!owner[0]) throw new Error(`items.create: request ${requestId} does not belong to organization ${orgId}`);
    const rows = await q<Item>(
      c,
      `insert into items (item_request_id, name, description, condition, product_url, quantity_requested, sort_order)
       values ($1, $2, $3, $4, $5, $6,
               coalesce($7, (select coalesce(max(sort_order), -1) + 1 from items where item_request_id = $1)))
       returning ${COLS}`,
      [
        requestId,
        input.name,
        input.description ?? null,
        input.condition ?? null,
        input.productUrl ?? null,
        input.quantityRequested,
        input.sortOrder ?? null,
      ],
    );
    const item = rows[0];
    if (!item) throw new Error("items.create returned no row");
    return item;
  });
}

/** Update item fields (MP-09 rows). Cannot touch claim counters by construction. */
export async function updateInTx(c: PoolClient, orgId: string, itemId: string, patch: UpdateItemPatch): Promise<Item> {
  const keys = Object.keys(patch) as (keyof UpdateItemPatch)[];
  if (keys.length === 0) throw new Error(`items.updateInTx: empty patch for ${itemId}`);
  const sets: string[] = [];
  const params: unknown[] = [itemId, orgId];
  for (const key of keys) {
    params.push(patch[key] ?? null);
    sets.push(`${PATCH_COLUMNS[key]} = $${params.length}`);
  }
  const rows = await q<Item>(
    c,
    `update items set ${sets.join(", ")}
      where id = $1 and item_request_id in (select id from item_requests where org_id = $2)
      returning ${COLS}`,
    params,
  );
  const item = rows[0];
  if (!item) throw new Error(`items.updateInTx: item ${itemId} not found in organization ${orgId}`);
  return item;
}

export async function update(ctx: DbContext, orgId: string, itemId: string, patch: UpdateItemPatch): Promise<Item> {
  const keys = Object.keys(patch) as (keyof UpdateItemPatch)[];
  if (keys.length === 0) {
    const existing = await getById(ctx, itemId);
    if (!existing) throw new Error(`items.update: not found: ${itemId}`);
    return existing;
  }
  return withDbContext(ctx, (c) => updateInTx(c, orgId, itemId, patch));
}

/**
 * Reconcile a request's editable item structure in a request-first,
 * child-second locked transaction. Existing activity remains attached to its
 * child: active children may be edited and reordered, but never removed, and
 * their requested quantity cannot drop below claims or receipts.
 */
export async function replaceForStaffEditInTx(
  c: PoolClient,
  requestId: string,
  rows: ReplaceItemInput[],
): Promise<Item[]> {
  const existing = await q<Item>(
    c,
    `select ${COLS}
       from items
      where item_request_id = $1
      order by id
      for update`,
    [requestId],
  );
  if (rows.length === 0) throw new RequestMustRetainAnItemError();
  const suppliedIds = rows.flatMap((row) => (row.id ? [row.id] : []));
  const suppliedIdSet = new Set(suppliedIds);
  for (const item of existing) {
    if (!suppliedIdSet.has(item.id)) {
      const hasHistory = (
        await q<{ exists: boolean }>(
          c,
          `select (
             $2::int > 0
             or $3::int > 0
             or exists(
               select 1
                 from item_pledge_lines line
                where line.item_id = $1
             )
           ) as exists`,
          [item.id, item.quantityClaimed, item.quantityReceived],
        )
      )[0]?.exists;
      if (hasHistory) throw new ItemWithActivityCannotBeRemovedError(item.name);
    }
  }

  const existingIds = new Set(existing.map((item) => item.id));
  if (new Set(suppliedIds).size !== suppliedIds.length || suppliedIds.some((id) => !existingIds.has(id))) {
    throw new UnknownItemOnRequestError();
  }

  const existingById = new Map(existing.map((item) => [item.id, item]));
  for (const row of rows) {
    if (!row.id) continue;
    const item = existingById.get(row.id);
    if (!item) throw new UnknownItemOnRequestError();
    const floor = Math.max(item.quantityClaimed, item.quantityReceived);
    if (row.quantityRequested < floor) {
      throw new ItemQuantityBelowParticipationError(item.name, floor);
    }
  }

  await q(c, `delete from items where item_request_id = $1 and not (id = any($2::uuid[]))`, [
    requestId,
    suppliedIds,
  ]);

  for (const [sortOrder, row] of rows.entries()) {
    if (row.id) {
      await q(
        c,
        `update items
            set name = $3, description = $4, condition = $5, product_url = $6,
                quantity_requested = $7, sort_order = $8
          where id = $2 and item_request_id = $1`,
        [requestId, row.id, row.name, row.description, row.condition, row.productUrl, row.quantityRequested, sortOrder],
      );
    } else {
      await q(
        c,
        `insert into items (item_request_id, name, description, condition, product_url, quantity_requested, sort_order)
         values ($1, $2, $3, $4, $5, $6, $7)`,
        [requestId, row.name, row.description, row.condition, row.productUrl, row.quantityRequested, sortOrder],
      );
    }
  }

  return q<Item>(c, `select ${COLS} from items where item_request_id = $1 order by sort_order asc, created_at asc`, [
    requestId,
  ]);
}

/** Number of items on a request (MP-07 must add at least one before submit). */
export async function countOnRequest(ctx: DbContext, requestId: string): Promise<number> {
  const rows = await withDbContext(ctx, (c) =>
    q<{ count: string }>(c, `select count(*)::text as count from items where item_request_id = $1`, [requestId]),
  );
  return Number(rows[0]?.count ?? 0);
}
