/**
 * Volunteer roles — child rows of a volunteer request. quantity_interested
 * moves ONLY through record_volunteer_signup() (replit.md rule 2);
 * quantity_remaining is generated by the database.
 */
import type { PoolClient } from "pg";
import { q, withDbContext, type DbContext } from "../db/client";
import type { VolunteerRole } from "../../shared/types";

const COLS = `id, legacy_wix_id as "legacyWixId", volunteer_request_id as "volunteerRequestId", name,
  description, quantity_needed as "quantityNeeded", quantity_interested as "quantityInterested",
  quantity_confirmed as "quantityConfirmed", quantity_remaining as "quantityRemaining",
  sort_order as "sortOrder", created_at as "createdAt", updated_at as "updatedAt"`;

export type CreateVolunteerRoleInput = {
  name: string;
  description?: string | null;
  quantityNeeded: number;
  sortOrder?: number;
};

/** Patch type deliberately has no quantityInterested/quantityRemaining. */
export type UpdateVolunteerRolePatch = Partial<{
  name: string;
  description: string | null;
  quantityNeeded: number;
  quantityConfirmed: number;
  sortOrder: number;
}>;

const PATCH_COLUMNS: Record<keyof UpdateVolunteerRolePatch, string> = {
  name: "name",
  description: "description",
  quantityNeeded: "quantity_needed",
  quantityConfirmed: "quantity_confirmed",
  sortOrder: "sort_order",
};

/** Roles of a request in sort order (MP-11 list, PB-04 table). */
export async function listByRequest(ctx: DbContext, requestId: string): Promise<VolunteerRole[]> {
  return withDbContext(ctx, (c) =>
    q<VolunteerRole>(
      c,
      `select ${COLS} from volunteer_roles where volunteer_request_id = $1 order by sort_order asc, created_at asc`,
      [requestId],
    ),
  );
}

export async function getById(ctx: DbContext, roleId: string): Promise<VolunteerRole | null> {
  const rows = await withDbContext(ctx, (c) =>
    q<VolunteerRole>(c, `select ${COLS} from volunteer_roles where id = $1`, [roleId]),
  );
  return rows[0] ?? null;
}

/** Add a role to a request (MP-11). Request must belong to the session organization. */
export async function create(
  ctx: DbContext,
  orgId: string,
  requestId: string,
  input: CreateVolunteerRoleInput,
): Promise<VolunteerRole> {
  return withDbContext(ctx, async (c) => {
    const owner = await q<{ id: string }>(c, `select id from volunteer_requests where id = $1 and org_id = $2`, [
      requestId,
      orgId,
    ]);
    if (!owner[0])
      throw new Error(`volunteerRoles.create: request ${requestId} does not belong to organization ${orgId}`);
    const rows = await q<VolunteerRole>(
      c,
      `insert into volunteer_roles (volunteer_request_id, name, description, quantity_needed, sort_order)
       values ($1, $2, $3, $4,
               coalesce($5, (select coalesce(max(sort_order), -1) + 1 from volunteer_roles where volunteer_request_id = $1)))
       returning ${COLS}`,
      [requestId, input.name, input.description ?? null, input.quantityNeeded, input.sortOrder ?? null],
    );
    const role = rows[0];
    if (!role) throw new Error("volunteerRoles.create returned no row");
    return role;
  });
}

/** Update role fields (MP-12 rows). Cannot touch interest counters by construction. */
export async function updateInTx(
  c: PoolClient,
  orgId: string,
  roleId: string,
  patch: UpdateVolunteerRolePatch,
): Promise<VolunteerRole> {
  const keys = Object.keys(patch) as (keyof UpdateVolunteerRolePatch)[];
  if (keys.length === 0) throw new Error(`volunteerRoles.updateInTx: empty patch for ${roleId}`);
  const sets: string[] = [];
  const params: unknown[] = [roleId, orgId];
  for (const key of keys) {
    params.push(patch[key] ?? null);
    sets.push(`${PATCH_COLUMNS[key]} = $${params.length}`);
  }
  const rows = await q<VolunteerRole>(
    c,
    `update volunteer_roles set ${sets.join(", ")}
      where id = $1 and volunteer_request_id in (select id from volunteer_requests where org_id = $2)
      returning ${COLS}`,
    params,
  );
  const role = rows[0];
  if (!role) throw new Error(`volunteerRoles.updateInTx: role ${roleId} not found in organization ${orgId}`);
  return role;
}

export async function update(
  ctx: DbContext,
  orgId: string,
  roleId: string,
  patch: UpdateVolunteerRolePatch,
): Promise<VolunteerRole> {
  const keys = Object.keys(patch) as (keyof UpdateVolunteerRolePatch)[];
  if (keys.length === 0) {
    const existing = await getById(ctx, roleId);
    if (!existing) throw new Error(`volunteerRoles.update: not found: ${roleId}`);
    return existing;
  }
  return withDbContext(ctx, (c) => updateInTx(c, orgId, roleId, patch));
}

/** Number of roles on a request (MP-10 must add at least one before submit). */
export async function countOnRequest(ctx: DbContext, requestId: string): Promise<number> {
  const rows = await withDbContext(ctx, (c) =>
    q<{ count: string }>(c, `select count(*)::text as count from volunteer_roles where volunteer_request_id = $1`, [
      requestId,
    ]),
  );
  return Number(rows[0]?.count ?? 0);
}
